[features]
seeds = false
skip-lint = false

[programs.localnet]
blockmine = "FgRe73gAkZPhxpiCFHMYMfLR4dabDaB1FDVFazVTcCtv"

[programs.devnet]
blockmine = "FgRe73gAkZPhxpiCFHMYMfLR4dabDaB1FDVFazVTcCtv"

[programs.mainnet]
blockmine = "FgRe73gAkZPhxpiCFHMYMfLR4dabDaB1FDVFazVTcCtv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[workspace]
types = "target/types"
